# Generated by Django 3.2.19 on 2024-04-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='time',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
